//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autolote
    {
        public Autolote()
        {
            this.ContactoAutolote = new HashSet<ContactoAutolote>();
            this.DireccionAutolote = new HashSet<DireccionAutolote>();
        }
    
        public int PK_Autolote { get; set; }
        public string NombreAutolote { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ContactoAutolote> ContactoAutolote { get; set; }
        public virtual ICollection<DireccionAutolote> DireccionAutolote { get; set; }
    }
}
