//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTipoMoneda
    {
        public CatalogoTipoMoneda()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
            this.Vehiculo1 = new HashSet<Vehiculo>();
        }
    
        public int PK_TipoMoneda { get; set; }
        public string TipoMoneda { get; set; }
        public string Simbolo { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo1 { get; set; }
    }
}
