//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoDepartamento
    {
        public CatalogoDepartamento()
        {
            this.DireccionEmpleado = new HashSet<DireccionEmpleado>();
            this.DireccionCliente = new HashSet<DireccionCliente>();
            this.DireccionProveedor = new HashSet<DireccionProveedor>();
            this.DireccionAutolote = new HashSet<DireccionAutolote>();
        }
    
        public int PK_Departamento { get; set; }
        public string NombreDepartamento { get; set; }
    
        public virtual ICollection<DireccionEmpleado> DireccionEmpleado { get; set; }
        public virtual ICollection<DireccionCliente> DireccionCliente { get; set; }
        public virtual ICollection<DireccionProveedor> DireccionProveedor { get; set; }
        public virtual ICollection<DireccionAutolote> DireccionAutolote { get; set; }
    }
}
