//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraVehiculo
    {
        public CompraVehiculo()
        {
            this.DetalleCompraVehiculo = new HashSet<DetalleCompraVehiculo>();
        }
    
        public int PK_CompraVehiculo { get; set; }
        public Nullable<int> FK_Proveedor { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public string NumCompra { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public bool Anulada { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<DetalleCompraVehiculo> DetalleCompraVehiculo { get; set; }
    }
}
