//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoEmpleado
    {
        public int PK_ContactoEmpleado { get; set; }
        public Nullable<int> FK_TipoContacto { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public string DetalleContacto { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual TipoContacto TipoContacto { get; set; }
    }
}
