//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuerpoVehiculo
    {
        public CuerpoVehiculo()
        {
            this.ModeloVehiculo = new HashSet<ModeloVehiculo>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int PK_CuerpoVehiculo { get; set; }
        public string CuerpoVehiculo1 { get; set; }
    
        public virtual ICollection<ModeloVehiculo> ModeloVehiculo { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
