//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaVehiculo
    {
        public int PK_DetalleVentaVehiculo { get; set; }
        public Nullable<int> FK_VentaVehiculo { get; set; }
        public Nullable<int> FK_Vehiculo { get; set; }
        public decimal Precio { get; set; }
        public Nullable<bool> Anulada { get; set; }
    
        public virtual VentaVehiculo VentaVehiculo { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
