//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompraVehiculo
    {
        public int PK_DetalleCompraVehiculo { get; set; }
        public Nullable<int> FK_CompraVehiculo { get; set; }
        public Nullable<int> FK_Vehiculo { get; set; }
        public decimal Precio { get; set; }
        public bool Anulada { get; set; }
    
        public virtual CompraVehiculo CompraVehiculo { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
