//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DireccionEmpleado
    {
        public int PK_DireccionEmpleado { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public Nullable<int> FK_Pais { get; set; }
        public Nullable<int> FK_Ciudad { get; set; }
        public Nullable<int> FK_Departamento { get; set; }
        public string Direccion { get; set; }
        public bool Active { get; set; }
    
        public virtual CatalogoCiudad CatalogoCiudad { get; set; }
        public virtual CatalogoDepartamento CatalogoDepartamento { get; set; }
        public virtual CatalogoPais CatalogoPais { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
