//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.CompraVehiculo = new HashSet<CompraVehiculo>();
            this.ContactoEmpleado = new HashSet<ContactoEmpleado>();
            this.DireccionEmpleado = new HashSet<DireccionEmpleado>();
            this.IdentificacionEmpleado = new HashSet<IdentificacionEmpleado>();
            this.VentaVehiculo = new HashSet<VentaVehiculo>();
        }
    
        public int PK_Empleado { get; set; }
        public Nullable<int> FK_TipoEmpleado { get; set; }
        public string NumEmpleado { get; set; }
        public string PrimerNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoNombre { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CompraVehiculo> CompraVehiculo { get; set; }
        public virtual ICollection<ContactoEmpleado> ContactoEmpleado { get; set; }
        public virtual ICollection<DireccionEmpleado> DireccionEmpleado { get; set; }
        public virtual TipoEmpleado TipoEmpleado { get; set; }
        public virtual ICollection<IdentificacionEmpleado> IdentificacionEmpleado { get; set; }
        public virtual ICollection<VentaVehiculo> VentaVehiculo { get; set; }
    }
}
