//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificacionProveedor
    {
        public int PK_IdentificacionProveedor { get; set; }
        public Nullable<int> FK_TipoIdentificacion { get; set; }
        public Nullable<int> FK_Proveedor { get; set; }
        public string NumIdentificacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoIdentificacion TipoIdentificacion { get; set; }
    }
}
