//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcaVehiculo
    {
        public MarcaVehiculo()
        {
            this.ModeloVehiculo = new HashSet<ModeloVehiculo>();
        }
    
        public int PK_MarcaVehiculo { get; set; }
        public Nullable<int> FK_Pais { get; set; }
        public string MarcaVehiculo1 { get; set; }
        public Nullable<int> AnioFundacion { get; set; }
        public bool Active { get; set; }
    
        public virtual CatalogoPais CatalogoPais { get; set; }
        public virtual ICollection<ModeloVehiculo> ModeloVehiculo { get; set; }
    }
}
