//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoContacto
    {
        public TipoContacto()
        {
            this.ContactoAutolote = new HashSet<ContactoAutolote>();
            this.ContactoCliente = new HashSet<ContactoCliente>();
            this.ContactoEmpleado = new HashSet<ContactoEmpleado>();
            this.ContactoProveedor = new HashSet<ContactoProveedor>();
        }
    
        public int PK_TipoContacto { get; set; }
        public string TipoContacto1 { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ContactoAutolote> ContactoAutolote { get; set; }
        public virtual ICollection<ContactoCliente> ContactoCliente { get; set; }
        public virtual ICollection<ContactoEmpleado> ContactoEmpleado { get; set; }
        public virtual ICollection<ContactoProveedor> ContactoProveedor { get; set; }
    }
}
