//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCliente
    {
        public TipoCliente()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int PK_TipoCliente { get; set; }
        public string TipoCliente1 { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
