//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIdentificacion
    {
        public TipoIdentificacion()
        {
            this.IdentificacionCliente = new HashSet<IdentificacionCliente>();
            this.IdentificacionEmpleado = new HashSet<IdentificacionEmpleado>();
            this.IdentificacionProveedor = new HashSet<IdentificacionProveedor>();
        }
    
        public int PK_TipoIdentificacion { get; set; }
        public string TipoIdentificacion1 { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<IdentificacionCliente> IdentificacionCliente { get; set; }
        public virtual ICollection<IdentificacionEmpleado> IdentificacionEmpleado { get; set; }
        public virtual ICollection<IdentificacionProveedor> IdentificacionProveedor { get; set; }
    }
}
