//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaVehiculo
    {
        public VentaVehiculo()
        {
            this.DetalleVentaVehiculo = new HashSet<DetalleVentaVehiculo>();
        }
    
        public int PK_VentaVehiculo { get; set; }
        public Nullable<int> FK_Empleado { get; set; }
        public Nullable<int> FK_Cliente { get; set; }
        public string NumVenta { get; set; }
        public Nullable<bool> Cotizar { get; set; }
        public Nullable<bool> Anulada { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<DetalleVentaVehiculo> DetalleVentaVehiculo { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
